version: '3'

services:
  api:
    image: ucekmez/ex-api
    container_name: "api"
    build:
      context: ./API
      dockerfile: Dockerfile
    networks:
      - all
    expose:
      - "7778"
    ports:
      - "7778:7778"

  ui:
    image: ucekmez/ex-ui
    container_name: "ui"
    networks:
      - all
    build:
      context: ./UI
      dockerfile: Dockerfile
    expose:
      - "7779"
    ports:
      - "7779:7779"
    depends_on:
      - api


networks:
  all:
