version: '3'

services:
  database:
    image: mongo
    container_name: "database"
    volumes:
          - ./database:/data/db
    expose:
      - "7777"
    ports:
      - "7777:27017"

  api:
    image: ucekmez/ex-api
    container_name: "api"
    build:
      context: ./API
      dockerfile: Dockerfile
    expose:
      - "7778"
    ports:
      - "7778:7778"
    links:
      - database
    depends_on:
      - database

  ui:
    image: ucekmez/ex-ui
    container_name: "ui"
    build:
      context: ./UI
      dockerfile: Dockerfile
    expose:
      - "7779"
    ports:
      - "7779:7779"
    links:
      - api
    depends_on:
      - api
